spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  server:
    port: 8080
    context-path: /
  datasource:
    url: jdbc:mysql://192.168.1.141:3306/ofs?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&useAffectedRows=true&allowPublicKeyRetrieval=true
    username: ofuser
    password: ofuser
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  devtools:
    restart:
      enabled: true  #设置开启热部署
  logging:
    config: classpath:src/test/resources/log4j2.yml
debug: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql